/**
 * Writes this package's shipped tile documentation into a committed source
 * module as raw markdown keyed by content key: the base name, without its `.md`
 * extension, of the file that carries it. Run through
 * `npm run generate:tile-docs` after editing a page under
 * `targets/<target>/docs/<locale>/tiles/`.
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

/** Package root, one level above this script. */
const PACKAGE_DIR = resolve(dirname(fileURLToPath(import.meta.url)), "..");

/** Target whose shipped tile documentation is carried into a source module. */
const TARGET = "microbit-v2";

/** Locale the carried documentation is read from. */
const LOCALE = "en";

/** Directory holding the target's shipped tile documentation. */
const CONTENT_DIR = join(PACKAGE_DIR, "targets", TARGET, "docs", LOCALE, "tiles");

/** Module the carried documentation is written to. */
const OUT_FILE = join(PACKAGE_DIR, "src", "targets", TARGET, "mindcraft", "_generated", "tile-doc-content.ts");

/** Every `.md` file in `directory` as raw markdown keyed by content key, in name order. */
function readMarkdown(directory: string): Record<string, string> {
  const content: Record<string, string> = {};
  for (const file of readdirSync(directory).sort()) {
    if (!file.endsWith(".md")) continue;
    content[file.slice(0, -3)] = readFileSync(join(directory, file), "utf8");
  }
  return content;
}

/** Escape `text` for embedding in a template literal. */
function escapeTemplateLiteral(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

/** The source of the module carrying `content`. */
function moduleSource(content: Record<string, string>): string {
  const lines = [
    "// Auto-generated by scripts/generate-tile-doc-content.ts -- DO NOT EDIT",
    "",
    'import type { TileDocContent } from "@mindcraft-lang/assistant-bridge/kit";',
    "",
    "/**",
    " * The English documentation this target ships for its own tiles, as raw",
    " * markdown keyed by content key: the base name, without its `.md` extension,",
    " * of the file that carries it.",
    " */",
    "export const MICROBIT_V2_TILE_DOC_CONTENT: TileDocContent = {",
  ];
  for (const [contentKey, markdown] of Object.entries(content)) {
    lines.push(`  "${contentKey}": \`${escapeTemplateLiteral(markdown)}\`,`);
  }
  lines.push("};", "");
  return lines.join("\n");
}

const content = readMarkdown(CONTENT_DIR);
mkdirSync(dirname(OUT_FILE), { recursive: true });
writeFileSync(OUT_FILE, moduleSource(content), "utf8");
console.log(`tile docs: carried ${Object.keys(content).length} pages into ${relative(PACKAGE_DIR, OUT_FILE)}`);
