// Auto-generated by scripts/build-docs.mjs -- DO NOT EDIT

export const tileContent: Record<string, string> = {
  "actuator-display-clear": `\`\`\`brain noframe do
{ "tile": "tile.actuator->microbit-v2.display-clear" }
\`\`\`

# Clear display

Turns off every LED of the 5x5 display.

---

Turns off all 25 LEDs at once, leaving the display blank. It takes no settings.
The clear is instant and takes over the display right away, ending a running
text scroll or image draw.
`,
  "actuator-display-text": `\`\`\`brain noframe do
{ "tile": "tile.actuator->microbit-v2.display-scroll" }
\`\`\`

# Display text

Scrolls text across the display.

---

Scrolls the text from right to left and ends with a blank display; a single
character is shown still for a moment instead of scrolling. With no
\`tile:tile.parameter->microbit-v2.text\` argument it shows the value the WHEN
side produced, or "hello". The rule waits until the animation finishes, and a
request made while the display is busy is dropped; add
\`tile:tile.modifier->microbit-v2.immediately\` to take over the display at once,
or \`tile:tile.modifier->microbit-v2.in-background\` to let the rule continue
without waiting.
`,
  "actuator-draw-image": `\`\`\`brain noframe do
{ "tile": "tile.actuator->microbit-v2.draw-image" }
\`\`\`

# Draw image

Shows one or more images on the display.

---

Draws each given \`tile:tile.parameter->microbit-v2.image\` in order, holding
each for \`tile:tile.parameter->microbit-v2.duration\` seconds (default 1
second); the last image stays on the display. With no image it draws
\`tile:tile.literal->struct:<Image>->happy\`. The rule waits for the hold to
finish, and a draw made while the display is busy is dropped; add
\`tile:tile.modifier->microbit-v2.immediately\` to take over the display at once,
or \`tile:tile.modifier->microbit-v2.in-background\` to let the rule continue
without waiting. A duration of 0 paints the image and continues at once.
`,
  "actuator-play-sound": `\`\`\`brain noframe do
{ "tile": "tile.actuator->microbit-v2.play-sound" }
\`\`\`

# Play sound

Plays a built-in sound on the speaker.

---

Plays the given \`tile:tile.parameter->microbit-v2.sound-emoji\`, a built-in
sound such as \`tile:tile.literal->struct:<SoundEmoji>->twinkle\`. With no sound
it plays \`tile:tile.literal->struct:<SoundEmoji>->hello\`. The rule waits until
the sound finishes, and a play made while the speaker is busy is dropped; add
\`tile:tile.modifier->microbit-v2.immediately\` to take over the speaker at
once, or \`tile:tile.modifier->microbit-v2.in-background\` to let the rule
continue without waiting.
`,
  "actuator-radio-send": `\`\`\`brain noframe do
{ "tile": "tile.actuator->microbit-v2.radio-send" }
\`\`\`

# Radio send

Broadcasts a value to every micro:bit on the same radio group.

---

Sends a number, text, true/false, or a buffer over radio; with no argument it
sends the value the WHEN side produced. A true/false is sent as the number 1
or 0. The receiving micro:bit reads it with the matching radio receive tile and
must be on the same group (see
\`tile:tile.actuator->microbit-v2.set-radio-group\`).
`,
  "actuator-set-pixel": `\`\`\`brain noframe do
{ "tile": "tile.actuator->microbit-v2.display-set-pixel" }
\`\`\`

# Set pixel

Sets one LED of the 5x5 display.

---

Lights a single LED. \`tile:tile.parameter->microbit-v2.x\` picks the column and
\`tile:tile.parameter->microbit-v2.y\` the row, each 0 to 4 counted from the top
left (default 0); \`tile:tile.parameter->microbit-v2.brightness\` is 0 (off) to
255 (full, the default). The write is instant and is not blocked by a running
text scroll or image draw.
`,
  "actuator-set-radio-group": `\`\`\`brain noframe do
{ "tile": "tile.actuator->microbit-v2.set-radio-group" }
\`\`\`

# Set radio group

Chooses which radio group this micro:bit talks on.

---

Sets the radio group to a number from 0 to 255; with no argument it sets the
default group 0. Micro:bits only hear each other when their groups match, so
set the same group on both ends, usually when the page is entered.
`,
  "literal-image-arrow-east": `\`\`\`brain noframe do
{ "tile": "tile.literal->struct:<Image>->arrow-east" }
\`\`\`

# Arrow east

The built-in right-pointing arrow image.

---

A ready-made 5x5 image for \`tile:tile.actuator->microbit-v2.draw-image\`.
`,
  "literal-image-arrow-north": `\`\`\`brain noframe do
{ "tile": "tile.literal->struct:<Image>->arrow-north" }
\`\`\`

# Arrow north

The built-in up-pointing arrow image.

---

A ready-made 5x5 image for \`tile:tile.actuator->microbit-v2.draw-image\`.
`,
  "literal-image-arrow-south": `\`\`\`brain noframe do
{ "tile": "tile.literal->struct:<Image>->arrow-south" }
\`\`\`

# Arrow south

The built-in down-pointing arrow image.

---

A ready-made 5x5 image for \`tile:tile.actuator->microbit-v2.draw-image\`.
`,
  "literal-image-arrow-west": `\`\`\`brain noframe do
{ "tile": "tile.literal->struct:<Image>->arrow-west" }
\`\`\`

# Arrow west

The built-in left-pointing arrow image.

---

A ready-made 5x5 image for \`tile:tile.actuator->microbit-v2.draw-image\`.
`,
  "literal-image-happy": `\`\`\`brain noframe do
{ "tile": "tile.literal->struct:<Image>->happy" }
\`\`\`

# Happy

The built-in happy face image.

---

A ready-made 5x5 image for \`tile:tile.actuator->microbit-v2.draw-image\`. This is also the image drawn when the draw image tile is given no image.
`,
  "literal-image-heart": `\`\`\`brain noframe do
{ "tile": "tile.literal->struct:<Image>->heart" }
\`\`\`

# Heart

The built-in heart image.

---

A ready-made 5x5 image for \`tile:tile.actuator->microbit-v2.draw-image\`.
`,
  "literal-image-sad": `\`\`\`brain noframe do
{ "tile": "tile.literal->struct:<Image>->sad" }
\`\`\`

# Sad

The built-in sad face image.

---

A ready-made 5x5 image for \`tile:tile.actuator->microbit-v2.draw-image\`.
`,
  "literal-sound-giggle": `\`\`\`brain noframe do
{ "tile": "tile.literal->struct:<SoundEmoji>->giggle" }
\`\`\`

# Giggle

A giggling sound.

---

A ready-made sound for \`tile:tile.actuator->microbit-v2.play-sound\`.
`,
  "literal-sound-happy": `\`\`\`brain noframe do
{ "tile": "tile.literal->struct:<SoundEmoji>->happy" }
\`\`\`

# Happy

A cheerful, upbeat sound.

---

A ready-made sound for \`tile:tile.actuator->microbit-v2.play-sound\`.
`,
  "literal-sound-hello": `\`\`\`brain noframe do
{ "tile": "tile.literal->struct:<SoundEmoji>->hello" }
\`\`\`

# Hello

A short greeting sound.

---

A ready-made sound for \`tile:tile.actuator->microbit-v2.play-sound\`.
`,
  "literal-sound-mysterious": `\`\`\`brain noframe do
{ "tile": "tile.literal->struct:<SoundEmoji>->mysterious" }
\`\`\`

# Mysterious

A long, eerie sound.

---

A ready-made sound for \`tile:tile.actuator->microbit-v2.play-sound\`.
`,
  "literal-sound-sad": `\`\`\`brain noframe do
{ "tile": "tile.literal->struct:<SoundEmoji>->sad" }
\`\`\`

# Sad

A drooping, unhappy sound.

---

A ready-made sound for \`tile:tile.actuator->microbit-v2.play-sound\`.
`,
  "literal-sound-slide": `\`\`\`brain noframe do
{ "tile": "tile.literal->struct:<SoundEmoji>->slide" }
\`\`\`

# Slide

A sliding-down sound.

---

A ready-made sound for \`tile:tile.actuator->microbit-v2.play-sound\`.
`,
  "literal-sound-soaring": `\`\`\`brain noframe do
{ "tile": "tile.literal->struct:<SoundEmoji>->soaring" }
\`\`\`

# Soaring

A long rising flight of sound.

---

A ready-made sound for \`tile:tile.actuator->microbit-v2.play-sound\`.
`,
  "literal-sound-spring": `\`\`\`brain noframe do
{ "tile": "tile.literal->struct:<SoundEmoji>->spring" }
\`\`\`

# Spring

A boingy, bouncing sound.

---

A ready-made sound for \`tile:tile.actuator->microbit-v2.play-sound\`.
`,
  "literal-sound-twinkle": `\`\`\`brain noframe do
{ "tile": "tile.literal->struct:<SoundEmoji>->twinkle" }
\`\`\`

# Twinkle

A long sparkling chime.

---

A ready-made sound for \`tile:tile.actuator->microbit-v2.play-sound\`.
`,
  "literal-sound-yawn": `\`\`\`brain noframe do
{ "tile": "tile.literal->struct:<SoundEmoji>->yawn" }
\`\`\`

# Yawn

A slow, sleepy sound.

---

A ready-made sound for \`tile:tile.actuator->microbit-v2.play-sound\`.
`,
  "modifier-click": `\`\`\`brain noframe when
{ "tile": "tile.modifier->microbit-v2.click" }
\`\`\`

# Click

Reacts to a short press and release.

---

Attach to a button tile such as \`tile:tile.sensor->microbit-v2.button-a\`: the
rule fires when the button is released after a press shorter than one second.
A longer press is a \`tile:tile.modifier->microbit-v2.long-click\` instead.
`,
  "modifier-double-click": `\`\`\`brain noframe when
{ "tile": "tile.modifier->microbit-v2.double-click" }
\`\`\`

# Double click

Reacts to two quick presses.

---

Attach to a button tile such as \`tile:tile.sensor->microbit-v2.button-a\`: the
rule fires when a second press starts within half a second of a click.
`,
  "modifier-face-down": `\`\`\`brain noframe when
{ "tile": "tile.modifier->microbit-v2.face-down" }
\`\`\`

# Face down

Detects the micro:bit lying flat, display down.

---

Attach to \`tile:tile.sensor->microbit-v2.gesture\`: the rule fires while the
board lies flat with the display facing down.
`,
  "modifier-face-up": `\`\`\`brain noframe when
{ "tile": "tile.modifier->microbit-v2.face-up" }
\`\`\`

# Face up

Detects the micro:bit lying flat, display up.

---

Attach to \`tile:tile.sensor->microbit-v2.gesture\`: the rule fires while the
board lies flat with the display facing up.
`,
  "modifier-freefall": `\`\`\`brain noframe when
{ "tile": "tile.modifier->microbit-v2.freefall" }
\`\`\`

# Freefall

Detects the micro:bit falling.

---

Attach to \`tile:tile.sensor->microbit-v2.gesture\`: the rule fires while the
board is falling freely, such as when it is dropped or tossed.
`,
  "modifier-held": `\`\`\`brain noframe when
{ "tile": "tile.modifier->microbit-v2.held" }
\`\`\`

# Held

True the whole time a button is down.

---

Attach to a button tile such as \`tile:tile.sensor->microbit-v2.button-a\`: the
rule keeps firing on every think while the button is held, not just on the
press.
`,
  "modifier-immediately": `\`\`\`brain noframe do
{ "tile": "tile.modifier->microbit-v2.immediately" }
\`\`\`

# Immediately

Takes over the display or speaker at once.

---

Attach to \`tile:tile.actuator->microbit-v2.display-scroll\`,
\`tile:tile.actuator->microbit-v2.draw-image\`, or
\`tile:tile.actuator->microbit-v2.play-sound\`: whatever is showing or playing
is stopped and this one starts now. Without it, a request made while the
display or speaker is busy is dropped.
`,
  "modifier-in-background": `\`\`\`brain noframe do
{ "tile": "tile.modifier->microbit-v2.in-background" }
\`\`\`

# In background

Runs the show or sound without making the rule wait.

---

Attach to \`tile:tile.actuator->microbit-v2.display-scroll\`,
\`tile:tile.actuator->microbit-v2.draw-image\`, or
\`tile:tile.actuator->microbit-v2.play-sound\`: the animation or sound runs as
usual, but the rule continues at once instead of waiting for it to finish. The
display or speaker stays busy until it completes, so a new request during that
time is still dropped.
`,
  "modifier-long-click": `\`\`\`brain noframe when
{ "tile": "tile.modifier->microbit-v2.long-click" }
\`\`\`

# Long click

Reacts to a long press and release.

---

Attach to a button tile such as \`tile:tile.sensor->microbit-v2.button-a\`: the
rule fires when the button is released after being held for one second or more.
`,
  "modifier-pressed": `\`\`\`brain noframe when
{ "tile": "tile.modifier->microbit-v2.pressed" }
\`\`\`

# Pressed

Reacts the moment a button goes down.

---

Attach to a button tile such as \`tile:tile.sensor->microbit-v2.button-a\`: the
rule fires on the think the button is first pressed. This is also what a bare
button tile detects.
`,
  "modifier-released": `\`\`\`brain noframe when
{ "tile": "tile.modifier->microbit-v2.released" }
\`\`\`

# Released

Reacts the moment a button comes back up.

---

Attach to a button tile such as \`tile:tile.sensor->microbit-v2.button-a\`: the
rule fires on the think the button is let go.
`,
  "modifier-shake": `\`\`\`brain noframe when
{ "tile": "tile.modifier->microbit-v2.shake" }
\`\`\`

# Shake

Detects the micro:bit being shaken.

---

Attach to \`tile:tile.sensor->microbit-v2.gesture\` to detect shaking. This is
also what a bare gesture tile detects.
`,
  "modifier-tilt-down": `\`\`\`brain noframe when
{ "tile": "tile.modifier->microbit-v2.tilt-down" }
\`\`\`

# Tilt down

Detects the micro:bit tilted down.

---

Attach to \`tile:tile.sensor->microbit-v2.gesture\`: the rule fires while the
board is tilted down. It stays true for as long as the board is held in that
position.
`,
  "modifier-tilt-left": `\`\`\`brain noframe when
{ "tile": "tile.modifier->microbit-v2.tilt-left" }
\`\`\`

# Tilt left

Detects the micro:bit tilted left.

---

Attach to \`tile:tile.sensor->microbit-v2.gesture\`: the rule fires while the
board is tilted left. It stays true for as long as the board is held in that
position.
`,
  "modifier-tilt-right": `\`\`\`brain noframe when
{ "tile": "tile.modifier->microbit-v2.tilt-right" }
\`\`\`

# Tilt right

Detects the micro:bit tilted right.

---

Attach to \`tile:tile.sensor->microbit-v2.gesture\`: the rule fires while the
board is tilted right. It stays true for as long as the board is held in that
position.
`,
  "modifier-tilt-up": `\`\`\`brain noframe when
{ "tile": "tile.modifier->microbit-v2.tilt-up" }
\`\`\`

# Tilt up

Detects the micro:bit tilted up.

---

Attach to \`tile:tile.sensor->microbit-v2.gesture\`: the rule fires while the
board is tilted up. It stays true for as long as the board is held in that
position.
`,
  "parameter-brightness": `\`\`\`brain noframe do
{ "tile": "tile.parameter->microbit-v2.brightness" }
\`\`\`

# Brightness

How brightly an LED lights.

---

Gives \`tile:tile.actuator->microbit-v2.display-set-pixel\` its brightness, a
number from 0 (off) to 255 (full). When left off, the pixel is set to full
brightness; use 0 to turn a pixel off.
`,
  "parameter-duration": `\`\`\`brain noframe do
{ "tile": "tile.parameter->microbit-v2.duration" }
\`\`\`

# Duration

How long an image is held, in seconds.

---

Gives \`tile:tile.actuator->microbit-v2.draw-image\` its hold time per image, in
seconds. When left off, each image is held for 1 second; a duration of 0
paints the image and lets the rule continue at once.
`,
  "parameter-image": `\`\`\`brain noframe do
{ "tile": "tile.parameter->microbit-v2.image" }
\`\`\`

# Image

An image to show on the display.

---

Gives \`tile:tile.actuator->microbit-v2.draw-image\` an image to draw: a built-in
image such as \`tile:tile.literal->struct:<Image>->heart\` or an image variable.
Add more than one to play them in a sequence, each held for the duration.
`,
  "parameter-sound": `\`\`\`brain noframe do
{ "tile": "tile.parameter->microbit-v2.sound-emoji" }
\`\`\`

# Sound

A sound to play on the speaker.

---

Gives \`tile:tile.actuator->microbit-v2.play-sound\` a sound to play: a built-in
sound such as \`tile:tile.literal->struct:<SoundEmoji>->happy\` or a sound
variable.
`,
  "parameter-text": `\`\`\`brain noframe do
{ "tile": "tile.parameter->microbit-v2.text" }
\`\`\`

# Text

The text to show on the display.

---

Gives \`tile:tile.actuator->microbit-v2.display-scroll\` the text to scroll.
When left off, the actuator shows the value the WHEN side produced, or
"hello".
`,
  "parameter-x": `\`\`\`brain noframe do
{ "tile": "tile.parameter->microbit-v2.x" }
\`\`\`

# X

The column of a display pixel.

---

Gives \`tile:tile.actuator->microbit-v2.display-set-pixel\` its column, a number
from 0 (left) to 4 (right). When left off, the column is 0.
`,
  "parameter-y": `\`\`\`brain noframe do
{ "tile": "tile.parameter->microbit-v2.y" }
\`\`\`

# Y

The row of a display pixel.

---

Gives \`tile:tile.actuator->microbit-v2.display-set-pixel\` its row, a number
from 0 (top) to 4 (bottom). When left off, the row is 0.
`,
  "sensor-button-a": `\`\`\`brain noframe when
{ "tile": "tile.sensor->microbit-v2.button-a" }
\`\`\`

# Button A

True when something happens on button A.

---

Place on the **WHEN** side to react to button A. The optional modifier picks the
event: \`tile:tile.modifier->microbit-v2.pressed\` (the default) fires on the think
the button goes down, \`tile:tile.modifier->microbit-v2.released\` when it comes
back up, \`tile:tile.modifier->microbit-v2.click\` after a short press,
\`tile:tile.modifier->microbit-v2.double-click\` on two quick presses,
\`tile:tile.modifier->microbit-v2.long-click\` after a press held for a second or
more, and \`tile:tile.modifier->microbit-v2.held\` is true the whole time the
button is down.
`,
  "sensor-button-ab": `\`\`\`brain noframe when
{ "tile": "tile.sensor->microbit-v2.button-ab" }
\`\`\`

# Button A+B

True when buttons A and B are used together.

---

Works like \`tile:tile.sensor->microbit-v2.button-a\`, but the press only counts
while **both** buttons are down at the same time. It takes the same optional
event modifiers: \`tile:tile.modifier->microbit-v2.pressed\` (the default),
\`tile:tile.modifier->microbit-v2.released\`,
\`tile:tile.modifier->microbit-v2.click\`,
\`tile:tile.modifier->microbit-v2.double-click\`,
\`tile:tile.modifier->microbit-v2.long-click\`, and
\`tile:tile.modifier->microbit-v2.held\`.
`,
  "sensor-button-b": `\`\`\`brain noframe when
{ "tile": "tile.sensor->microbit-v2.button-b" }
\`\`\`

# Button B

True when something happens on button B.

---

Place on the **WHEN** side to react to button B. The optional modifier picks the
event: \`tile:tile.modifier->microbit-v2.pressed\` (the default) fires on the think
the button goes down, \`tile:tile.modifier->microbit-v2.released\` when it comes
back up, \`tile:tile.modifier->microbit-v2.click\` after a short press,
\`tile:tile.modifier->microbit-v2.double-click\` on two quick presses,
\`tile:tile.modifier->microbit-v2.long-click\` after a press held for a second or
more, and \`tile:tile.modifier->microbit-v2.held\` is true the whole time the
button is down.
`,
  "sensor-gesture": `\`\`\`brain noframe when
{ "tile": "tile.sensor->microbit-v2.gesture" }
\`\`\`

# Gesture

True while the micro:bit is in the selected motion or orientation.

---

Reads the accelerometer and is true while the current gesture matches the
selected modifier word; with no word it detects
\`tile:tile.modifier->microbit-v2.shake\`. The words are
\`tile:tile.modifier->microbit-v2.shake\`,
\`tile:tile.modifier->microbit-v2.tilt-up\`,
\`tile:tile.modifier->microbit-v2.tilt-down\`,
\`tile:tile.modifier->microbit-v2.tilt-left\`,
\`tile:tile.modifier->microbit-v2.tilt-right\`,
\`tile:tile.modifier->microbit-v2.face-up\`,
\`tile:tile.modifier->microbit-v2.face-down\`, and
\`tile:tile.modifier->microbit-v2.freefall\`.
`,
  "sensor-logo": `\`\`\`brain noframe when
{ "tile": "tile.sensor->microbit-v2.button-logo" }
\`\`\`

# Logo

True when the touch logo is touched.

---

The gold logo on the front of the micro:bit is touch sensitive and behaves like
a third button. It takes the same optional event modifiers as
\`tile:tile.sensor->microbit-v2.button-a\`:
\`tile:tile.modifier->microbit-v2.pressed\` (the default),
\`tile:tile.modifier->microbit-v2.released\`,
\`tile:tile.modifier->microbit-v2.click\`,
\`tile:tile.modifier->microbit-v2.double-click\`,
\`tile:tile.modifier->microbit-v2.long-click\`, and
\`tile:tile.modifier->microbit-v2.held\`.
`,
  "sensor-radio-receive-buffer": `\`\`\`brain noframe when
{ "tile": "tile.sensor->microbit-v2.radio-receive-buffer" }
\`\`\`

# Radio receive buffer

Fires when a buffer of raw bytes arrives over radio.

---

Delivers the next unread buffer packet, one per think, oldest first; the
received bytes are the tile's result, and the packet also fills the
\`received value\` and \`signal strength\` output tiles for the DO side. Buffers
carry custom packet formats, such as the gamepad state packet a library
decodes. Both micro:bits must be on the same radio group (see
\`tile:tile.actuator->microbit-v2.set-radio-group\`).
`,
  "sensor-radio-receive-number": `\`\`\`brain noframe when
{ "tile": "tile.sensor->microbit-v2.radio-receive-number" }
\`\`\`

# Radio receive number

Fires when a number arrives over radio.

---

Delivers the next unread number packet, one per think, oldest first; the
received number is the tile's result, and the packet also fills the
\`received value\` and \`signal strength\` output tiles for the DO side. A received
0 still fires the rule. Both micro:bits must be on the same radio group (see
\`tile:tile.actuator->microbit-v2.set-radio-group\`).
`,
  "sensor-radio-receive-string": `\`\`\`brain noframe when
{ "tile": "tile.sensor->microbit-v2.radio-receive-string" }
\`\`\`

# Radio receive string

Fires when text arrives over radio.

---

Delivers the next unread text packet, one per think, oldest first; the received
text is the tile's result, and the packet also fills the \`received value\` and
\`signal strength\` output tiles for the DO side. Empty text still fires the
rule. Both micro:bits must be on the same radio group (see
\`tile:tile.actuator->microbit-v2.set-radio-group\`).
`,
};

export const patternContent: Record<string, string> = {
  "button-press-response": `# Respond to a Button Press

Patterns are reusable rule shapes you can adapt to your own brain. Each pattern
page shows a complete rule; use the **Copy** button to copy it, paste it into
the brain editor, then swap tiles to fit your project.

This one is the most common shape on the micro:bit: when a button is pressed,
show something on the display.

## Rules

\`\`\`brain
{
  "ruleJsons": [
    {
      "version": 1,
      "when": [
        "tile.sensor->microbit-v2.button-a",
        "tile.modifier->microbit-v2.pressed"
      ],
      "do": [
        "tile.actuator->microbit-v2.display-scroll",
        "tile.literal->string:<string>->hi"
      ],
      "children": []
    }
  ],
  "catalog": [
    {
      "version": 2,
      "kind": "literal",
      "tileId": "tile.literal->string:<string>->hi",
      "valueType": "string:<string>",
      "value": "hi",
      "valueLabel": "hi",
      "displayFormat": "default"
    }
  ]
}
\`\`\`

## See Also

\`tile:tile.sensor->microbit-v2.button-a\`
\`tile:tile.modifier->microbit-v2.pressed\`
\`tile:tile.actuator->microbit-v2.display-scroll\`
`,
};
