#!/usr/bin/env node

// ---------------------------------------------------------------------------
// build-docs.mjs -- Reads .md files under src/docs/content/{locale}/tiles/,
// src/docs/content/{locale}/patterns/, and src/docs/content/{locale}/concepts/
// and generates a TypeScript module per locale at
// src/docs/_generated/{locale}.ts, exporting:
//
//   tileContent: Record<string, string> -- keyed by filename stem
//   patternContent: Record<string, string> -- keyed by filename stem
//   conceptContent: Record<string, string> -- keyed by filename stem
//
// Run after editing content (npm run generate:docs); the generated module is
// committed. The docs registry spec asserts the generated module matches the
// .md files on disk, so a stale module fails `npm test`.
// ---------------------------------------------------------------------------

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const CONTENT_DIR = path.join(ROOT, "src", "docs", "content");
const OUT_DIR = path.join(ROOT, "src", "docs", "_generated");

/** Read all .md files from a directory and return { stem: content } pairs. */
function readMdFiles(dir) {
  if (!fs.existsSync(dir)) return {};
  const entries = {};
  for (const file of fs.readdirSync(dir).sort()) {
    if (!file.endsWith(".md")) continue;
    entries[file.slice(0, -3)] = fs.readFileSync(path.join(dir, file), "utf-8");
  }
  return entries;
}

/** Escape a string for embedding in a JS template literal. */
function escapeTemplateLiteral(str) {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

/** Generate a TypeScript module string for one locale. */
function generateLocaleModule(tilesMap, patternsMap, conceptsMap) {
  const lines = ["// Auto-generated by scripts/build-docs.mjs -- DO NOT EDIT", ""];
  for (const [exportName, map] of [
    ["tileContent", tilesMap],
    ["patternContent", patternsMap],
    ["conceptContent", conceptsMap],
  ]) {
    lines.push(`export const ${exportName}: Record<string, string> = {`);
    for (const [stem, content] of Object.entries(map)) {
      lines.push(`  "${stem}": \`${escapeTemplateLiteral(content)}\`,`);
    }
    lines.push("};");
    lines.push("");
  }
  return lines.join("\n");
}

fs.mkdirSync(OUT_DIR, { recursive: true });

const locales = fs
  .readdirSync(CONTENT_DIR, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort();

for (const locale of locales) {
  const tilesMap = readMdFiles(path.join(CONTENT_DIR, locale, "tiles"));
  const patternsMap = readMdFiles(path.join(CONTENT_DIR, locale, "patterns"));
  const conceptsMap = readMdFiles(path.join(CONTENT_DIR, locale, "concepts"));
  const outFile = path.join(OUT_DIR, `${locale}.ts`);
  fs.writeFileSync(outFile, generateLocaleModule(tilesMap, patternsMap, conceptsMap), "utf-8");
  console.log(
    `docs: generated ${locale}.ts (${Object.keys(tilesMap).length} tiles, ${Object.keys(patternsMap).length} patterns, ${Object.keys(conceptsMap).length} concepts)`
  );
}
