#!/usr/bin/env node

// ---------------------------------------------------------------------------
// build-docs.mjs -- Reads .md files under src/docs/content/{locale}/tiles/
// and generates a TypeScript module per locale at
// src/docs/_generated/{locale}.ts, exporting:
//
//   tileContent: Record<string, string> -- keyed by filename stem
//
// Run after editing content (npm run generate:docs); the generated module is
// committed. The docs registry spec asserts the generated module matches the
// .md files on disk, so a stale module fails `npm test`.
// ---------------------------------------------------------------------------

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const CONTENT_DIR = path.join(ROOT, "src", "docs", "content");
const OUT_DIR = path.join(ROOT, "src", "docs", "_generated");

/** Read all .md files from a directory and return { stem: content } pairs. */
function readMdFiles(dir) {
  if (!fs.existsSync(dir)) return {};
  const entries = {};
  for (const file of fs.readdirSync(dir).sort()) {
    if (!file.endsWith(".md")) continue;
    entries[file.slice(0, -3)] = fs.readFileSync(path.join(dir, file), "utf-8");
  }
  return entries;
}

/** Escape a string for embedding in a JS template literal. */
function escapeTemplateLiteral(str) {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

/** Generate a TypeScript module string for one locale. */
function generateLocaleModule(tilesMap) {
  const lines = ["// Auto-generated by scripts/build-docs.mjs -- DO NOT EDIT", ""];
  lines.push("export const tileContent: Record<string, string> = {");
  for (const [stem, content] of Object.entries(tilesMap)) {
    lines.push(`  "${stem}": \`${escapeTemplateLiteral(content)}\`,`);
  }
  lines.push("};");
  lines.push("");
  return lines.join("\n");
}

fs.mkdirSync(OUT_DIR, { recursive: true });

const locales = fs
  .readdirSync(CONTENT_DIR, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort();

for (const locale of locales) {
  const tilesMap = readMdFiles(path.join(CONTENT_DIR, locale, "tiles"));
  const outFile = path.join(OUT_DIR, `${locale}.ts`);
  fs.writeFileSync(outFile, generateLocaleModule(tilesMap), "utf-8");
  console.log(`docs: generated ${locale}.ts (${Object.keys(tilesMap).length} tiles)`);
}
